# Import libraries

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Generating random data

In [2]:
x=np.array([4,6,8,12,14,20]).reshape((-1,1))
y=np.array([8,12,18,20,26,30])

In [3]:
x

array([[ 4],
       [ 6],
       [ 8],
       [12],
       [14],
       [20]])

In [4]:
y

array([ 8, 12, 18, 20, 26, 30])

# Linear Regression model and fitting on data

In [5]:
lin=LinearRegression()

In [6]:
lin=lin.fit(x,y)

# Finding slope and intercept

In [7]:
lin.coef_

array([1.36153846])

In [8]:
lin.intercept_

4.476923076923075

In [9]:
#y=.1.361*x+4.476

# Predictions

In [10]:
pred=np.array([24,36]).reshape((-1,1))
lin.predict(pred)

array([37.15384615, 53.49230769])