# Importing libraries

In [1]:
import tensorflow as tf

In [23]:
#for creating and removing a directory (folder), fetching its contents, changing and identifying the current directory

In [22]:
import os

# Stored the image path for reading the images

In [59]:
images_ds=tf.data.Dataset.list_files("pepper/*/*",shuffle=False)

In [60]:
for images in images_ds.take(3):
    print(images.numpy())

b'pepper\\Pepper__bell___Bacterial_spot\\0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\006adb74-934f-448f-a14f-62181742127b___JR_B.Spot 3395.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\00f2e69a-1e56-412d-8a79-fdce794a17e4___JR_B.Spot 3132.JPG'


# Shuffling the images

In [61]:
images_ds=images_ds.shuffle(200)

In [62]:
for images in images_ds.take(3):
    print(images.numpy())

b'pepper\\Pepper__bell___Bacterial_spot\\11092e1c-9fdc-4405-85b9-a8d7548f12bb___JR_B.Spot 9051.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\311c06b4-36e7-4fc7-840d-2f3f86d28ea5___JR_B.Spot 3350.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\284b0fae-ce3c-43e7-acc6-e9a22bd6eb6f___JR_B.Spot 9074.JPG'


In [63]:
class_names=["Pepper__bell___Bacterial_spot","Pepper__bell___healthy"]

In [64]:
image_count=len(images_ds)
image_count

1994

# Splitting the dataset

In [65]:
train_size=int(image_count*0.8)
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [66]:
len(train_ds)

1595

In [67]:
len(test_ds)

399

# Retrieve the label for image path

In [68]:
s='pepper\\Pepper__bell___Bacterial_spot\\0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG'
s=s.split("\\")

In [69]:
s

['pepper',
 'Pepper__bell___Bacterial_spot',
 '0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG']

In [70]:
s[-2]

'Pepper__bell___Bacterial_spot'

In [71]:
def get_label(file_path):
    return tf.strings.split(file_path,os.path.sep)[-2]

# Reading the data

In [72]:
def process_image(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    return img,label

In [73]:
for t in train_ds.take(4):
    print(t.numpy())

b'pepper\\Pepper__bell___Bacterial_spot\\301b41f3-647f-4bd2-9adb-ef98c8b8c238___JR_B.Spot 3399.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\01940b6d-7dea-4889-a7b8-a35f4e9bba34___NREC_B.Spot 9120.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\1cb295da-e568-4168-a29c-48ab980f3772___NREC_B.Spot 9250.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\31add1a3-eab6-4c9c-946f-d85d89297a0e___NREC_B.Spot 1842.JPG'


# map function applies get element function to each elements in training dataset

In [74]:
for label in train_ds.map(get_label).take(4):
    print(label)

tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)


In [75]:
#x is the image data
#y is the labels

# Printing both x and y

In [76]:
for img,label in train_ds.map(process_image).take(1):
    print("Image:",img)
    print("Label:",label)

Image: tf.Tensor(
[[[183.25 164.25 157.25]
  [189.75 170.75 163.75]
  [221.25 202.75 195.75]
  ...
  [177.25 160.25 152.25]
  [166.75 149.75 141.75]
  [171.25 154.25 146.25]]

 [[175.5  156.5  149.5 ]
  [153.   134.   127.  ]
  [161.25 142.25 135.25]
  ...
  [172.   155.   147.  ]
  [158.25 141.25 133.25]
  [173.5  156.5  148.5 ]]

 [[164.75 145.75 138.75]
  [132.25 113.25 106.25]
  [171.   152.   145.  ]
  ...
  [160.25 143.25 135.25]
  [170.   153.   145.  ]
  [148.25 131.25 123.25]]

 ...

 [[159.   126.   109.  ]
  [140.75 107.75  90.75]
  [158.   125.   108.  ]
  ...
  [149.75 123.75 108.75]
  [162.5  136.5  121.5 ]
  [157.   131.   116.  ]]

 [[164.25 131.25 114.25]
  [164.75 131.75 114.75]
  [147.25 114.25  97.25]
  ...
  [156.75 130.75 115.75]
  [152.75 126.75 111.75]
  [160.   134.   119.  ]]

 [[162.   129.   112.  ]
  [154.   121.   104.  ]
  [154.25 121.25 104.25]
  ...
  [136.   110.    95.  ]
  [154.75 128.75 113.75]
  [143.25 117.25 102.25]]], shape=(128, 128, 3), dtype=

In [77]:
train_ds=train_ds.map(process_image)

# Now it is a numpy array and we have to scale it

In [78]:
def scale(image,label):
    return image/255,label

In [79]:
train_ds=train_ds.map(scale)
for image,label in train_ds.take(3):
    print("Image:",image.numpy()[0][0])
    print("Label:",label.numpy())

Image: [0.63235295 0.59313726 0.63235295]
Label: b'Pepper__bell___Bacterial_spot'
Image: [0.672549   0.62941176 0.64509803]
Label: b'Pepper__bell___Bacterial_spot'
Image: [0.67941177 0.6480392  0.6401961 ]
Label: b'Pepper__bell___Bacterial_spot'
