# Importing libraries

In [1]:
import tensorflow as tf

In [23]:
#for creating and removing a directory (folder), fetching its contents, changing and identifying the current directory

In [22]:
import os

# Stored the image path for reading the images

In [36]:
images_ds=tf.data.Dataset.list_files("pepper/*/*",shuffle=False)

In [37]:
for images in images_ds.take(3):
    print(images.numpy())

b'pepper\\Pepper__bell___Bacterial_spot\\0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\006adb74-934f-448f-a14f-62181742127b___JR_B.Spot 3395.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\00f2e69a-1e56-412d-8a79-fdce794a17e4___JR_B.Spot 3132.JPG'


# Shuffling the images

In [38]:
images_ds=images_ds.shuffle(200)

In [39]:
for images in images_ds.take(3):
    print(images.numpy())

b'pepper\\Pepper__bell___Bacterial_spot\\31add1a3-eab6-4c9c-946f-d85d89297a0e___NREC_B.Spot 1842.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\11b85334-0029-430e-873d-9402bd9e5e9f___JR_B.Spot 9031.JPG'


In [40]:
class_names=["Pepper__bell___Bacterial_spot","Pepper__bell___healthy"]

In [41]:
image_count=len(images_ds)
image_count

1994

# Splitting the dataset

In [42]:
train_size=int(image_count*0.8)
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [43]:
len(train_ds)

1595

In [44]:
len(test_ds)

399

# Retrieve the label for image path

In [45]:
s='pepper\\Pepper__bell___Bacterial_spot\\0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG'
s=s.split("\\")

In [46]:
s

['pepper',
 'Pepper__bell___Bacterial_spot',
 '0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG']

In [47]:
s[-2]

'Pepper__bell___Bacterial_spot'

In [48]:
def get_label(file_path):
    return tf.strings.split(file_path,os.path.sep)[-2]

# Reading the data

In [49]:
def process_image(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    return img,label

In [50]:
for t in train_ds.take(4):
    print(t.numpy())

b'pepper\\Pepper__bell___Bacterial_spot\\0a0dbf1f-1131-496f-b337-169ec6693e6f___NREC_B.Spot 9241.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\02baf62e-11e2-4dde-97fb-e369b57d55d3___JR_B.Spot 8971.JPG'
b'pepper\\Pepper__bell___Bacterial_spot\\12342367-f62b-40d0-897b-77bd1edbd3d1___JR_B.Spot 3199.JPG'


# map function applies get element function to each elements in training dataset

In [51]:
for label in train_ds.map(get_label):
    print(label)

tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shap

tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shap

tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___Bacterial_spot', shap

tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell___healthy', shape=(), dtype=string)
tf.Tensor(b'Pepper__bell

In [52]:
#x is the image data
#y is the labels

# Printing both x and y

In [53]:
for img,label in train_ds.map(process_image).take(1):
    print("Image:",img)
    print("Label:",label)

Image: tf.Tensor(
[[[167.   162.   168.  ]
  [158.25 153.25 159.25]
  [165.   160.   166.  ]
  ...
  [105.25  98.25 105.25]
  [128.25 121.25 128.25]
  [114.75 107.75 114.75]]

 [[166.   161.   167.  ]
  [164.75 159.75 165.75]
  [169.   164.   170.  ]
  ...
  [115.25 108.25 115.25]
  [113.75 106.75 113.75]
  [129.   122.   129.  ]]

 [[165.25 160.25 166.25]
  [157.25 152.25 158.25]
  [166.   161.   167.  ]
  ...
  [124.75 117.75 124.75]
  [111.5  104.5  111.5 ]
  [121.75 114.75 121.75]]

 ...

 [[159.25 153.25 155.25]
  [152.   146.   148.  ]
  [162.   156.   158.  ]
  ...
  [110.5  104.5  106.5 ]
  [113.75 107.75 109.75]
  [108.5  102.5  104.5 ]]

 [[154.   148.   150.  ]
  [160.25 154.25 156.25]
  [157.5  151.5  153.5 ]
  ...
  [114.   108.   110.  ]
  [106.75 100.75 102.75]
  [109.75 103.75 105.75]]

 [[154.   148.   150.  ]
  [154.25 148.25 150.25]
  [156.75 150.75 152.75]
  ...
  [ 99.25  93.25  95.25]
  [115.   109.   111.  ]
  [117.25 111.25 113.25]]], shape=(128, 128, 3), dtype=

In [54]:
train_ds=train_ds.map(process_image)

# Now it is a numpy array and we have to scale it

In [55]:
def scale(image,label):
    return image/255,label

In [57]:
train_ds=train_ds.map(scale)
for image,label in train_ds.take(3):
    print("Image:",image.numpy()[0][0])
    print("Label:",label.numpy())

Image: [0.00259516 0.00247213 0.00228758]
Label: b'Pepper__bell___Bacterial_spot'
Image: [0.00296424 0.00288735 0.00298731]
Label: b'Pepper__bell___Bacterial_spot'
Image: [0.00280661 0.00263745 0.00269896]
Label: b'Pepper__bell___Bacterial_spot'
